#!/usr/bin/env bash

SESSION_NAME=work

# Working directory (Fill out with where repo is)
# SESSION_WD=~/dev

if [ -z "$SESSION_WD" ]; then
  echo "You need to set SESSION_WD"
  exit 1
fi

# How large the split is
SPLIT_PER=25

# Check if our tmux session already exists
tmux has-session -t $SESSION_NAME > /dev/null 2>&1
if [ $? != 0 ]
then
  # Create a new session, in detached
  tmux new-session -s $SESSION_NAME -d
  # cd to the correct directory
  tmux send-keys -t $SESSION_NAME "cd $SESSION_WD" C-m 
  # Start up vim
  tmux send-keys -t $SESSION_NAME "vim" C-m

  # Split the window horizontally, to a percentage defined by SPLIT_PER
  tmux split-window -h -p $SPLIT_PER -t $SESSION_NAME
  # Split pane 1 (the second pane) vertically
  tmux split-window -v -t $SESSION_NAME:0.1
  # Split pane 2 (the second pane) vertically by 50%
  tmux split-window -v -p 50 -t $SESSION_NAME:0.2

  # Do pane one stuff
  # cd to the correct directory, window 0, pane 1
  tmux send-keys -t $SESSION_NAME:0.1 "cd $SESSION_WD" C-m 
  # Clear the pane
  tmux send-keys -t $SESSION_NAME:0.1 "clear" C-m 
  tmux send-keys -t $SESSION_NAME:0.1 "npm run dev" C-m

  # Do pane two stuff
  # cd to the correct directory, window 0, pane 2
  tmux send-keys -t $SESSION_NAME:0.2 "cd $SESSION_WD" C-m 
  tmux send-keys -t $SESSION_NAME:0.2 "clear" C-m 
  # Clear the pane
  tmux send-keys -t $SESSION_NAME:0.2 "d" C-m

  # Do pane three stuff
  # cd to the correct directory, window 0, pane 3
  tmux send-keys -t $SESSION_NAME:0.3 "cd $SESSION_WD" C-m 
  # Clear the pane
  tmux send-keys -t $SESSION_NAME:0.3 "clear" C-m 
  tmux select-window -t $SESSION_NAME:0.0
fi 
# Attach to the session we created above
tmux attach -t $SESSION_NAME
# Start up mongod
sudo service mongod stop > /dev/null 2>&1

PURPLE='\e[1;35m'
NC='\e[0m' # No Color

